main: powercivs.PowerCivs
name: PowerCivs
version: 1.0
load: STARTUP
author: Carter_Rogers
commands:
 asset:
  description: registers assets.
  usage: /asset <name> <amount>
 c:
  description: enters commands for corporations
  usage: /c <command> <arguments>
 corporation:
  description: enters commands for corporations
  usage: /corporation <command> <arguments>
 list:
  description: info
  usage: /list <tolist>
 saven:
  description: mod option to save towns.
  usage: /saven
 taxes:
  description: forces taxes to be taken out
  usage: /taxes
 n:
  description: enters nations commands.
  usage: /n <command> <arguments>
 nation:
  description: enters nation commands.
  usage: /nation <command> <arguments>
 register:
  description: registers a corporation or nation.
  usage: /register <type> <name>
 claim:
  description: claims a chunk for a nation.
  usage: /claim
 bal:
  description: checks player economy balance.
  usage: /bal
 balance:
  description: checks player economy balance.
  usage: /balance
 accept:
  description: accepts a request from a nation
  usage: /accept <nation>
 money:
  description: checks player economy balance.
  usage: /bal